=== Blockchain-explore/wallet-registry/wallet.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Cosmos Wallet",
  "description": "Cosmos Wallet.json is a metadata file that contains information about a wallet of a specific platform and which chains it supports, either natively or via custom client-side addition.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "wallet_name": {
      "type": "string",
      "pattern": "[a-z]+"
    },
    "pretty_name": {
      "type": "string"
    },
    "website": {
      "type": "string",
      "format": "url"
    },
    "git_repo": {
      "type": "string",
      "format": "url"
    },
    "platforms": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "browser_extension",
          "desktop_app",
          "mobile_app"
        ],
        "minContains": 1
      }
    },
    "has_suggest_feature": {
      "type": "boolean"
    },
    "supported_chains": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "[a-z]+"
      },
      "minContains": 1
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "wallet_name",
    "pretty_name",
    "platforms",
    "supported_chains"
  ]
}

=== Blockchain-explore/wallet-registry/wallets/keplrextension.json
{
  "$schema": "../wallet.schema.json",
  "wallet_name": "keplrextension",
  "pretty_name": "Keplr Wallet (Browser Extension)",
  "website": "https://www.keplr.app/",
  "platforms": [
    "browser_extension"
  ],
  "has_suggest_feature": true,
  "supported_chains": [
    "cosmoshub",
    "osmosis"
  ]
}
